### ISSUE TITLE
I used every step again and again but my service provider is not loading into bagisto

### ISSUE THREAD

**Issue by niraj-lal-rahi** [bagisto/bagisto-package-generator#18]
I have generated package with the same example give but it is not working.

steps :  https://devdocs.bagisto.com/1.x/packages/create_package.html#_1-by-using-bagisto-package-generator

Any help will be appreciated.
Thanks

**Comment by hardkiffeur** [comment]
@niraj-lal-rahi 
have you test a : 
`php artisan view:clear` & `php artisan config:cache` ?
then go under /admin you have the new pakage no ?
Plus it seems by using the composer create_package the final structure .../views/shop is not right because we don't have the index.blade.php under the shop folder but under a default one !
But if you copy paste the index.blade.php under the /views/shop all seems ok and having response on front with ...'localwebsite'/'namePackage'
